random_seed = 0


[downloads]
rc_api_url = "http://localhost:5572"
datasets = [
  "asap",
  # "ballroom",
  # "beatles",
  # "candombe",
  # "filosax",
  # "groove_midi",
  # "gtzan",
  # "guitarset",
  # "hainsworth",
  # "harmonix",
  # "hjdb",
  # "jaah",
  # "rwc",
  # "simac",
  # "smc",
  "tapcorrect",
]

[downloads.annotations]
github_user = "CPJKU"
github_repo = "beat_this_annotations"
github_branch = "main"

[downloads.spectrograms]
url_template = "https://zenodo.org/records/13922116/files/${dataset}.zip?download=1"


[paths]
models = "models"
downloads = "data/downloads"

[paths.data.raw]
annotations = "data/raw/annotations"
spectrograms = "data/raw/spectrogram"

[paths.data.interim]
annotations = "data/interim/annotations"

[paths.data.processed]
encoded_beats = "data/processed/encoded-annotations"
spectral_flux = "data/processed/spectral-flux"

[spectrogram]
sample_rate = 22050  # hz
n_fft = 1024
f_min = 30           # hz
f_max = 11000
n_mels = 128
mel_scale = "slaney"
hop_length = 441

[training]
train_ratio = 0.8
val_ratio = 0.1
# test_ratio = 0.1
batch_size = 4
learning_rate = 1e-5
