random_seed = 0


[downloads]
rc_api_url = "http://localhost:5572"
datasets = [
  # "asap",
  "ballroom",
  "beatles",
  "candombe",
  "filosax",
  "groove_midi",
  "gtzan",
  "guitarset",
  "hainsworth",
  "harmonix",
  "hjdb",
  "jaah",
  "rwc",
  # "simac",
  # "smc",
  "tapcorrect",
]

[downloads.annotations]
github_user = "CPJKU"
github_repo = "beat_this_annotations"
github_branch = "main"

[downloads.spectrograms]
url_template = "https://zenodo.org/records/13922116/files/${dataset}.zip?download=1"


[paths]
models = "models"
downloads = "data/downloads"
transitions = "models/transitions.npz"

[paths.data.raw]
annotations = "data/raw/annotations"
spectrograms = "data/raw/spectrogram"

[paths.data.interim]
annotations = "data/interim/annotations"

[paths.data.processed]
datasets_info = "data/interim/annotations/info.json"
splits_info = "data/processed/splits.csv"
annotations = "data/processed/encoded-annotations"
spectral_flux = "data/processed/spectral-flux"

[spectrogram]
sample_rate = 22050  # hz
n_fft = 1024
f_min = 30           # hz
f_max = 11000
n_mels = 128
mel_scale = "slaney"
hop_length = 441

[training]
train_ratio = 0.8
val_ratio = 0.1
# test_ratio = 0.1
batch_size = 16
max_batch_size = 4

[hypers]
learning_rate = 1e-3
dropout = 0.01
kernel_size = 3
channels = [64, 64, 64, 64, 64, 64, 64, 64]
dilations = [1, 2, 4, 8, 16, 32, 64, 128]
[post]
# standard metronome markings
tempo_bins = [40, 42, 50, 52, 54, 56, 58, 60, 63, 66, 69, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 126, 132, 138, 144, 152, 160, 168, 176, 184, 192, 200, 208]
# beats per bar
time_signatures = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
# parameters for beat period transition probability distribution
pi = 0.5183737879035278
lambda1 = 91795.4297938284
lambda2 = 14.551900090140123
